--
-- Data for TOC entry 79 (OID 62843039)
-- Name: pregunta_respuesta; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (1, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (2, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (3, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (4, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (5, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (6, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (7, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (8, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (9, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (10, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (11, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (12, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (13, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (14, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (15, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (16, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (17, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (18, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (19, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (20, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (21, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (22, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (23, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (24, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (25, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (26, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (27, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (28, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (29, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (30, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (31, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (32, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (33, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (34, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (35, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (36, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (37, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (38, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (39, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (40, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (41, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (42, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (43, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (44, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (45, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (46, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (47, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (48, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (49, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (1, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (2, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (3, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (4, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (5, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (6, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (7, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (8, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (9, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (10, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (11, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (12, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (13, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (14, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (15, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (16, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (17, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (18, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (19, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (20, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (21, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (22, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (23, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (24, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (25, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (26, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (27, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (28, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (29, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (30, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (31, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (32, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (33, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (34, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (35, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (36, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (37, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (38, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (39, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (40, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (41, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (42, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (43, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (44, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (45, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (46, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (47, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (48, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (49, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (1, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (2, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (3, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (4, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (5, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (6, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (7, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (8, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (9, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (10, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (11, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (12, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (13, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (14, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (15, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (16, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (17, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (18, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (19, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (20, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (21, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (22, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (23, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (24, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (25, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (26, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (27, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (28, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (29, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (30, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (31, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (32, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (33, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (34, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (35, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (36, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (37, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (38, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (39, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (40, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (41, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (42, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (43, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (44, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (45, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (46, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (47, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (48, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (49, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (1, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (2, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (3, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (4, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (5, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (6, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (7, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (8, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (9, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (10, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (11, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (12, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (13, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (14, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (15, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (16, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (17, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (18, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (19, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (20, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (21, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (22, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (23, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (24, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (25, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (26, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (27, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (28, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (29, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (30, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (31, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (32, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (33, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (34, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (35, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (36, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (37, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (38, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (39, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (40, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (41, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (42, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (43, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (44, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (45, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (46, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (47, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (48, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (49, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (1, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (2, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (3, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (4, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (5, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (6, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (7, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (8, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (9, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (10, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (11, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (12, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (13, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (14, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (15, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (16, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (17, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (18, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (19, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (20, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (21, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (22, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (23, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (24, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (25, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (26, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (27, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (28, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (29, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (30, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (31, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (32, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (33, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (34, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (35, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (36, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (37, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (38, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (39, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (40, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (41, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (42, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (43, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (44, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (45, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (46, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (47, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (48, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (49, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (1, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (2, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (3, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (4, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (5, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (6, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (7, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (8, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (9, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (10, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (11, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (12, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (13, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (14, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (15, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (16, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (17, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (18, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (19, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (20, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (21, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (22, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (23, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (24, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (25, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (26, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (27, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (28, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (29, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (30, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (31, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (32, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (33, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (34, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (35, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (36, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (37, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (38, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (39, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (40, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (41, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (42, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (43, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (44, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (45, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (46, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (47, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (48, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (49, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (1, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (2, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (3, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (4, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (5, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (6, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (7, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (8, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (9, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (10, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (11, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (12, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (13, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (14, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (15, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (16, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (17, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (18, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (19, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (20, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (21, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (22, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (23, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (24, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (25, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (26, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (27, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (28, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (29, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (30, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (31, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (32, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (33, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (34, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (35, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (36, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (37, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (38, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (39, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (40, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (41, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (42, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (43, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (44, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (45, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (46, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (47, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (48, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (49, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (50, 8, 1, 'Muy dificil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (51, 8, 1, 'Muy dificil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (52, 8, 1, 'Muy dificil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (53, 8, 1, 'Muy dificil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (54, 8, 1, 'Muy dificil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (55, 8, 1, 'Muy dificil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (56, 8, 1, 'Muy dificil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (50, 9, 2, 'Dificil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (51, 9, 2, 'Dificil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (52, 9, 2, 'Dificil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (53, 9, 2, 'Dificil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (54, 9, 2, 'Dificil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (55, 9, 2, 'Dificil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (56, 9, 2, 'Dificil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (50, 10, 3, 'A mi alcance');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (51, 10, 3, 'A mi alcance');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (52, 10, 3, 'A mi alcance');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (53, 10, 3, 'A mi alcance');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (54, 10, 3, 'A mi alcance');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (55, 10, 3, 'A mi alcance');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (56, 10, 3, 'A mi alcance');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (50, 11, 4, 'Facil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (51, 11, 4, 'Facil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (52, 11, 4, 'Facil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (53, 11, 4, 'Facil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (54, 11, 4, 'Facil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (55, 11, 4, 'Facil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (56, 11, 4, 'Facil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (50, 12, 5, 'Muy facil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (51, 12, 5, 'Muy facil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (52, 12, 5, 'Muy facil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (53, 12, 5, 'Muy facil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (54, 12, 5, 'Muy facil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (55, 12, 5, 'Muy facil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (56, 12, 5, 'Muy facil');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (57, 13, 1, 'Nunca');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (58, 13, 1, 'Nunca');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (57, 14, 2, 'Casi nunca');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (58, 14, 2, 'Casi nunca');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (57, 15, 3, 'Siempre');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (58, 15, 3, 'Siempre');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (50, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (51, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (52, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (53, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (54, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (55, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (56, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (57, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (58, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (61, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (62, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (63, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (64, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (65, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (66, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (67, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (68, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (69, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (61, 16, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (62, 16, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (63, 16, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (64, 16, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (65, 16, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (61, 17, 2, 'Mejorable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (62, 17, 2, 'Mejorable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (63, 17, 2, 'Mejorable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (64, 17, 2, 'Mejorable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (65, 17, 2, 'Mejorable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (61, 18, 3, 'Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (62, 18, 3, 'Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (63, 18, 3, 'Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (64, 18, 3, 'Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (65, 18, 3, 'Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (61, 19, 4, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (62, 19, 4, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (63, 19, 4, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (64, 19, 4, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (65, 19, 4, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (66, 20, 1, 'Para nada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (67, 20, 1, 'Para nada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (66, 21, 2, 'Un poco');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (67, 21, 2, 'Un poco');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (66, 22, 3, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (67, 22, 3, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (66, 23, 4, 'Bastante');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (67, 23, 4, 'Bastante');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (66, 24, 5, 'Totalmente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (67, 24, 5, 'Totalmente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (68, 25, 1, 'No');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (69, 25, 1, 'No');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (68, 26, 2, 'Si');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (69, 26, 2, 'Si');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (70, 27, 1, '1');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (70, 28, 2, '2');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (70, 29, 3, '3');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (70, 30, 4, '4');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (70, 31, 5, '5');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (71, 32, 1, 'Si');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (71, 33, 2, 'No');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (59, 34, 1, '1');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (60, 34, 1, '1');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (59, 35, 2, '2');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (60, 35, 2, '2');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (59, 36, 3, '3');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (60, 36, 3, '3');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (59, 37, 4, '4');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (60, 37, 4, '4');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (59, 38, 5, '5');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (60, 38, 5, '5');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (70, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (71, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (59, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (60, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (72, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (72, 2, 0, 'No Aplica');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (72, 3, 1, 'Deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (72, 4, 2, 'Regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (72, 5, 3, 'Aceptable');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (72, 6, 4, 'Bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (72, 7, 5, 'Excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (73, 39, 1, 'No');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (73, 40, 2, 'Algo');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (73, 41, 3, 'Medianamente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (73, 42, 4, 'Mucho');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (73, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (86, 43, 1, 'No');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (86, 44, 2, 'Si');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (86, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (87, 45, 1, 'muy deficiente ');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (88, 45, 1, 'muy deficiente ');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (89, 45, 1, 'muy deficiente ');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (87, 46, 2, 'deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (88, 46, 2, 'deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (89, 46, 2, 'deficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (87, 47, 3, 'suficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (88, 47, 3, 'suficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (89, 47, 3, 'suficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (87, 48, 4, 'mas que suficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (88, 48, 4, 'mas que suficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (89, 48, 4, 'mas que suficiente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (87, 49, 5, 'excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (88, 49, 5, 'excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (89, 49, 5, 'excelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (87, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (88, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (89, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (90, 50, 1, 'malo');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (91, 50, 1, 'malo');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (92, 50, 1, 'malo');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (90, 51, 2, 'regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (91, 51, 2, 'regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (92, 51, 2, 'regular');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (90, 52, 3, 'bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (91, 52, 3, 'bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (92, 52, 3, 'bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (90, 53, 4, 'muy bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (91, 53, 4, 'muy bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (92, 53, 4, 'muy bueno');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (90, 54, 5, 'exelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (91, 54, 5, 'exelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (92, 54, 5, 'exelente');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (90, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (91, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (92, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (74, 55, 1, 'Inadecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (75, 55, 1, 'Inadecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (76, 55, 1, 'Inadecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (77, 55, 1, 'Inadecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (78, 55, 1, 'Inadecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (79, 55, 1, 'Inadecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (80, 55, 1, 'Inadecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (81, 55, 1, 'Inadecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (82, 55, 1, 'Inadecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (83, 55, 1, 'Inadecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (84, 55, 1, 'Inadecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (85, 55, 1, 'Inadecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (74, 56, 2, 'Adecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (75, 56, 2, 'Adecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (76, 56, 2, 'Adecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (77, 56, 2, 'Adecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (78, 56, 2, 'Adecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (79, 56, 2, 'Adecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (80, 56, 2, 'Adecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (81, 56, 2, 'Adecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (82, 56, 2, 'Adecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (83, 56, 2, 'Adecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (84, 56, 2, 'Adecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (85, 56, 2, 'Adecuada');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (74, 57, 3, 'Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (75, 57, 3, 'Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (76, 57, 3, 'Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (77, 57, 3, 'Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (78, 57, 3, 'Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (79, 57, 3, 'Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (80, 57, 3, 'Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (81, 57, 3, 'Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (82, 57, 3, 'Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (83, 57, 3, 'Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (84, 57, 3, 'Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (85, 57, 3, 'Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (74, 58, 4, 'Muy Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (75, 58, 4, 'Muy Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (76, 58, 4, 'Muy Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (77, 58, 4, 'Muy Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (78, 58, 4, 'Muy Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (79, 58, 4, 'Muy Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (80, 58, 4, 'Muy Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (81, 58, 4, 'Muy Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (82, 58, 4, 'Muy Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (83, 58, 4, 'Muy Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (84, 58, 4, 'Muy Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (85, 58, 4, 'Muy Buena');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (74, 59, 5, 'Extraordinaria');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (75, 59, 5, 'Extraordinaria');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (76, 59, 5, 'Extraordinaria');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (77, 59, 5, 'Extraordinaria');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (78, 59, 5, 'Extraordinaria');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (79, 59, 5, 'Extraordinaria');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (80, 59, 5, 'Extraordinaria');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (81, 59, 5, 'Extraordinaria');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (82, 59, 5, 'Extraordinaria');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (83, 59, 5, 'Extraordinaria');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (84, 59, 5, 'Extraordinaria');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (85, 59, 5, 'Extraordinaria');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (74, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (75, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (76, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (77, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (78, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (79, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (80, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (81, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (82, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (83, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (84, 1, 0, 'No Contesto');
INSERT INTO pregunta_respuesta (id_pregunta, id_respuesta, valor, descripcion) VALUES (85, 1, 0, 'No Contesto');
