--
-- Data for TOC entry 76 (OID 62843020)
-- Name: pregunta; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (1, 'encuesta-est', 'Expuso claramente el programa al inicio del curso');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (2, 'encuesta-est', 'Informo con precision sobre el proceso de evaluacion');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (3, 'encuesta-est', 'Le dedica el tiempo apropiado a cada tema');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (4, 'encuesta-est', 'Desarrolla ordenadamente las actividades en clase');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (5, 'encuesta-est', 'Logra comunicarse efectivamente con el estudiante');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (6, 'encuesta-est', 'Orienta sobre el uso de libros, guias, materiales de apoyo y recursos tecnicos ');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (7, 'encuesta-est', 'Indica oportunamente la relacion entre los temas del curso');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (8, 'encuesta-est', 'Adapta sus explicaciones para hacerse entender mejor');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (9, 'encuesta-est', 'Mantiene un ambiente propicio para el aprendizaje');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (10, 'encuesta-est', 'Mantiene criterios claros de evaluacion');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (11, 'encuesta-est', 'Muestra disposicion para atender individualmente a los estudiantes');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (12, 'encuesta-est', 'Mantiene una actitud respetuosa hacia los estudiantes');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (13, 'encuesta-est', 'Es receptivo a las intervenciones de los estudiantes');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (14, 'encuesta-est', 'Cumple con el horario de clases establecido');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (15, 'encuesta-est', 'El contenido de los examenes se corresponde con lo explicado en clase');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (16, 'encuesta-est', 'Planifica tiempo suficiente para las evaluaciones');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (17, 'encuesta-est', 'Realiza la entrega y revision oportuna de los resultados de las evaluaciones');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (18, 'encuesta-est', 'Estimula la participacion del estudiante en el proceso de aprendizaje');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (19, 'encuesta-est', 'Motiva la busqueda activa de conocimiento');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (20, 'encuesta-est', 'Evalua el desempenio global del profesor');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (21, 'encuesta-est', 'Aprendizaje efectivo logrado en el curso');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (22, 'encuesta-est', 'Preparacion previa para cursar esta asignatura');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (23, 'encuesta-est', 'Dedicacion de tiempo y esfuerzo a este curso');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (24, 'encuesta-est', 'Calificacion que esperas obtener al final del curso');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (25, 'encuesta-est', 'Disponibilidad de libros, guias y materiales');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (26, 'encuesta-est', 'Contribuye significativamente a tu formacion profesional');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (27, 'encuesta-est', 'Existe equilibrio entre teoria y practica en el curso');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (28, 'encuesta-est', 'El esfuerzo requerido se corresponde con el numero de creditos');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (29, 'encuesta-est', 'La cantidad de contenidos es asimilable en un trimestre');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (30, 'encuesta-est', 'Asignale un puntaje al grado de dificultad del curso');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (31, 'encuesta-est', 'Expuso claramente el programa del laboratorio al inicio del curso');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (32, 'encuesta-est', 'Le dedica el tiempo apropiado a cada practica');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (33, 'encuesta-est', 'Desarrolla ordenadamente las actividades de laboratorio');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (34, 'encuesta-est', 'Indica oportunamente la relacion entre los temas de las diferentes practicas');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (35, 'encuesta-est', 'Explica claramente la relacion entre la teoria y las practicas de laboratorio');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (36, 'encuesta-est', 'Cumple a cabalidad las practicas programadas');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (37, 'encuesta-est', 'El contenido de los examenes se corresponde con las practicas respectivas');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (38, 'encuesta-est', 'Preparacion previa para cursar este laboratorio');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (39, 'encuesta-est', 'La dotacion de materiales y equipos es adecuada');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (40, 'encuesta-est', 'Las actividades estan bien planificadas para obtener resultados en el tiempo previsto');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (41, 'encuesta-est', 'Informa con precision sobre la manera de de evaluar la asignatura');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (42, 'encuesta-est', 'Orienta adecuadamente sobre el uso de libros, guias, materiales de apoyo y recursos tecnicos ');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (43, 'encuesta-est', 'Mantiene el interes de los estudiantes por el tema del curso');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (44, 'encuesta-est', 'Explica con claridad');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (45, 'encuesta-est', 'Esta dispuesto a atender a los estudiantes fuera del aula');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (46, 'encuesta-est', 'Muestra interes sobre el aprendizaje del estudiante');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (47, 'encuesta-est', 'Cumple cabalmente con el horario de clases establecido');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (48, 'encuesta-est', 'Motiva a la investigacion y busqueda personal');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (49, 'encuesta-est', 'Estimula el potencial intelectual del estudiante');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (50, 'gberrios', 'El nivel de las explicaciones en el texto Focus on Reading era...');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (51, 'gberrios', 'El nivel de las lecturas en la guia Reading Selections for ID-1112 era...');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (52, 'gberrios', 'El nivel de los programas de video o de audio del laboratorio era...');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (53, 'gberrios', 'Seguir la clase cuando se dictaba en ingles era...  ');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (54, 'gberrios', 'Salir bien en los examenes departamentales era...  ');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (55, 'gberrios', 'Salir bien en los examenes de laboratorio era...  ');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (56, 'gberrios', 'Salir bien en los examenes de clase era...  ');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (57, 'gsowie', '?Ha tenido necesidad de material adicional para cursar la asignatura?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (58, 'gsowie', '?Ha pedido apuntes prestados?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (59, 'jorgepacheco', 'Frecuencia del uso de la pagina web');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (60, 'jorgepacheco', 'Utilidad de la pagina web');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (61, 'williamc', '?Como le parecio el uso de la lista de correos del curso?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (62, 'williamc', '?Como le parecio la pagina web del curso?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (63, 'williamc', '?Como le parecieron los materiales desarrollados por el profesor y colocados en la pagina web del curso?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (64, 'williamc', '?Como le parecieron los materiales preparados por sus companieros de clase?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (65, 'williamc', '?Vale la pena el esfuerzo adicional que supone el soporte por internet?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (66, 'ecasanov', 'Considera util que se incorporen proyectos numericos en este curso?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (67, 'ecasanov', 'En el proyecto numerico el trabajo asignado esta en relacion con el % de nota en la evaluacion?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (68, 'ecasanov', 'Visito la pagina web del curso?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (69, 'ecasanov', 'Una pagina web del curso es util?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (70, 'crosi', '?Considera que el equipamiento del laboratorio es apropiado?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (71, 'aborges', '?Comprendio la aplicacion practica de esta asignatura a su profesion?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (72, 'encuesta-est', 'Que tanto avalaria que su profesor sea postulado al Premio a la Destacada Labor Docente');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (73, 'jstella', '?Considera Ud. provechosa la presencia de un profesor diferente en cada una de las dos areas de especialidad abarcadas en el curso? ');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (74, 'pbcelis', '?Como calificaria al Aula Virtual como herramienta de interaccion con el profesor?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (75, 'pbcelis', '?Como calificaria a la presentacion de la teoria en laminas de PowerPoint como herramienta de aprendizaje?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (76, 'pbcelis', '?Como calificaria al ejercicio practico realizado en clase como herramienta de fijacion de los conocimientos aprendidos en clase?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (77, 'pbcelis', '?Como calificaria a la Tarea Cuantitativa como herramienta de aprendizaje para la resolucion de problemas complejos?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (78, 'pbcelis', '?Como calificaria a la lectura de "papers" como herramienta de aprendizaje de puntos de vista diferentes en los temas tratados en clase?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (79, 'pbcelis', '?Como calificaria a la simulacion practica (juego del pull / juego TOC) como herramienta de fijacion de los conocimientos aprendidos en clase?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (80, 'pbcelis', '?Como calificaria al material audiovisual presentado en clase como herramienta de aprendizaje?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (81, 'pbcelis', '?Como calificaria a la lectura del libro "La Meta"  de Goldratt como herramienta de aprendizaje?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (82, 'pbcelis', '?Como calificaria al examen parcial como herramienta de aprendizaje y fijacion de conocimientos?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (83, 'pbcelis', '?Como calificaria al Trabajo de Investigacion como herramienta de aprendizaje de las caracteristicas de una Industria en particular?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (84, 'pbcelis', '?Como calificaria al tiempo destinado a consulta con el profesor como herramienta de aprendizaje y fijacion de conocimientos?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (85, 'pbcelis', '?Como calificaria al conjunto de herramientas utilizadas, en funcion del aprendizaje logrado por usted en el curso?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (86, 'jsananez', '?Le haria Ud. cambios al laboratorio de la asignatura?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (87, 'lordonez', 'Le fue util la materia para su accion como ciudadano?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (88, 'lordonez', 'Le ofrecio herramientas utiles para su acccion fuera de la universidad?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (89, 'lordonez', 'Como se compara con otros cursos en la misma area general?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (90, 'gsowie', 'soy bonito');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (91, 'gsowie', 'es esto util');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (92, 'gsowie', 'como cree que salga');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (93, 'encuesta-est', 'Escriba su opinion sobre la asignatura');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (94, 'ecasanov', 'Cual es su opinion sobre la pagina web y como se podria mejorar?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (95, 'lordonez', 'Recomendaciones para cursos futuros');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (96, 'jsananez', 'En caso de respuesta afirmativa, ?Que modificaciones sugiere?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (97, 'pbcelis', 'En sus propias palabras, indique que herramientas didacticas aniadiria, eliminaria, o cambiaria en este curso.');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (98, 'williamc', '?Como mejoraria la interaccion entre profesor y alumnos con las herramientas de internet de este curso?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (99, 'encuesta-est', 'Escriba su opinion sobre la asignatura');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (100, 'crosi', '?Introduciria cambios en el pensum de la carrera o del Lab para mejorar el aprovechamiento de este laboratorio?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (101, 'encuesta-est', 'Escriba su opinion sobre la asignatura');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (102, 'gsowie', '?Que fue lo usted considero mejor en el curso?');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (103, 'encuesta-est', 'Escriba su opinion sobre la asignatura');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (104, 'encuesta-est', 'Escriba su opinion sobre la asignatura');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (105, 'jorgepacheco', 'Que modificaciones le harian a la pagian web');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (106, 'gsowie', 'es esto un test? diga porque');
INSERT INTO pregunta (id_pregunta, "owner", enunciado) VALUES (107, 'aborges', 'Nombre los aspectos que Ud considera mejorables, tanto en el curso como del docente');
